repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: \.gitignore
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
        exclude: ^\.github/pull_request_template\.md$

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: text-unicode-replacement-char

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        args: ["--prose-wrap=always"]
        exclude: ^\.github/pull_request_template\.md$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

ci:
  autoupdate_schedule: quarterly
